allFields = [
    "id",
    "conf-init",
    "response-id",
    "conf-scenario-medical",
    "comp-scenario-medical-1",
    "comp-scenario-medical-2",
    "faq-page-time",
    "willingness-medical",
    "willingness-medical-text",
    "safety-medical-overall-init",
    "safety-medical-tee",
    "safety-medical-hospital",
    "safety-medical-people",
    "safety-medical-data",
    "safety-medical-purpose",
    "safety-medical-text",
    "questions-medical",
    "tee-concept-m1",
    "tee-concept-m2",
    "tee-concept-m3",
    "tee-concept-m4",
    "tee-concept-m5",
    "tee-concept-m6",
    "tee-concept-m7",
    "tee-concept-m8",
    "tee-concept-m9",
    "tee-concept-m10",
    "tee-concept-m11",
    "tee-concept-m12",
    "conf-tee-concept-medical",
    "conf-tee-medical",
    "safety-medical-overall-post",
    "conf-scenario-iot",
    "comp-scenario-iot-1",
    "comp-scenario-iot-2",
    "willingness-iot",
    "willingness-iot-text",
    "safety-iot-overall-init",
    "safety-iot-tee",
    "safety-iot-company",
    "safety-iot-people",
    "safety-iot-data",
    "safety-iot-purpose",
    "safety-iot-text",
    "questions-iot",
    "tee-concept-i1",
    "tee-concept-i2",
    "tee-concept-i3",
    "tee-concept-i4",
    "tee-concept-i5",
    "tee-concept-i6",
    "tee-concept-i7",
    "tee-concept-i8",
    "tee-concept-i9",
    "tee-concept-i10",
    "tee-concept-i11",
    "tee-concept-i12",
    "conf-tee-concept-iot",
    "conf-tee-iot",
    "safety-iot-overall-post",
    "demo-tee",
    "demo-tee-text",
    "demo-cs-employ",
    "demo-cs-employ-text",
    "demo-cs-education",
    "demo-cs-education-text",
    "demo-medical",
    "demo-medical-text",
    "demo-medical-employ",
    "demo-medical-employ-text",
    "demo-iot",
    "demo-iot-text",
    "demo-tap",
    "demo-tap-text",
    "age",
    "gender",
    "gender-text",
    "race",
    "race-text",
    "education",
    "feedback",
    "SCENARIO_Med",
    "SCENARIO_IoT",
    "Med_First",
    "EXPLN",
    "FAQ",
    "faq1_count",
    "faq2_count",
    "faq3_count",
    "M1",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "M7",
    "M8",
    "M9",
    "M10",
    "M11",
    "M12",
    "I1",
    "I2",
    "I3",
    "I4",
    "I5",
    "I6",
    "I7",
    "I8",
    "I9",
    "I10",
    "I11",
    "I12"
]

medicalScoreFields = [
    "SCENARIO_Med",
    "EXPLN",
    "FAQ",
    "faq1_count",
    "faq2_count",
    "faq3_count",
    "M1",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "M7",
    "M8",
    "M9",
    "M10",
    "M11",
    "M12"
]

iotScoreFields = [
    "SCENARIO_IoT",
    "EXPLN",
    "FAQ",
    "faq1_count",
    "faq2_count",
    "faq3_count",
    "I1",
    "I2",
    "I3",
    "I4",
    "I5",
    "I6",
    "I7",
    "I8",
    "I9",
    "I10",
    "I11",
    "I12"
]

qualCodes =[
    'Distrust:Vague',
    'Distrust:TEE',
    'Distrust:Scenario',
    'Distrust:Manufactuerer',
    'Risk:Hacking',
    'Risk:People',
    'Risk:General',
    'Risk:Real',
    'Risk:Fail',
    'Risk:Tamper',
    'Gen:Isolation',
    'Gen:How?',
    'Gen:Auth',
    'Gen:Implementation',
    'Gen:Features',
    'Gen:Answered',
    'Gen:Encryption',
    'Gen:Tech',
    'Gen:Transmit',
    'Gen:Misc',
    'Gen:Password',
    'Gen:Diff',
    "Gen:Open Source",
    "Gen:What?",
    "Gen:Untechnical",
    "Gen:Visual",
    'Use:Breaches',
    'Use:Request',
    'Use:Real',
    'Use:New',
    'Scenario:Data',
    'Scenario:People',
    'Scenario:Future',
    'Sceanrio:Fail',
    'Scenario:Positive',
    'Scenario:Incentive',
    'Scenario:Misc',
    'Guarantee:General',
    'Guarantee:Testing',
    'Guarantee:Reliable',
    'Guarantee:Cert'
]

qualCategories = [
    "distrust",
    "risk",
    "risk2",
    "gen",
    "gen2",
    "use",
    "scenario",
    "scenario2",
    "guarantees"
]

qualSafetyCodes =[
    'Distrust:Vague',
    'Distrust:Gen',
    'Distrust:Hacker',
    'Distrust:Breaches',
    'Distrust:Unnecessary',
    'Distrust:Future Use',
    'Distrust:AI',
    'Distrust:Bug',
    'Distrust:Sell',
    'Distrust:Transmission/Store',
    'Distrust:Lie',
    'Distrust:Research',
    'Distrust:"Trust"',
    'Distrust:Inference',
    'Distrust:Repeat Data',
    'Distrust:Repeat TEE',
    'Distrust:Repeat Destination',
    'Distrust:Repeat Purpose',
    'Distrust:Repeat People',
    'Trust:Vague',
    'Trust:Boring',
    'Trust:Crypto',
    'Trust:AI',
    'Trust:Transmission',
    'Trust:Real',
    'Trust:People',
    'Trust:"Trust"',
    'Trust:Masked',
    'Trust:Repeat Purpose',
    'Trust:Repeat TEE',
    'Trust:Repeat Destination',
    'Trust:Repeat Data',
    'Info:Sell',
    'Info:People',
    'Info:TEE',
    'Info:Destination',
    'Info:Data',
    'Info:Crypto',
    'Misc:Unclear',
    'Misc:Other Tech',
    'Misc:Do Not Want',
    'Misc:Despite Risk',
    'Misc:Inaccurate'
]

qualSafetyRepeat = [
'Distrust:Repeat Data',
    'Distrust:Repeat TEE',
    'Distrust:Repeat Destination',
    'Distrust:Repeat Purpose',
    'Distrust:Repeat People',
    'Trust:People',
    'Trust:Repeat Purpose',
    'Trust:Repeat TEE',
    'Trust:Repeat Destination',
    'Trust:Repeat Data'
]

qualSafetyCategories = [
    "distrust",
    "distrust2",
    "trust",
    "trust2",
    "info",
    "misc"
]